package create;

import entite.Player;
import entite.Lesson;
import static interfaces.Log.LOG;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.time.Instant;
import java.time.LocalDateTime;
import utils.DBConnection;
import static utils.LCUtil.showMessageFatal;
import static utils.LCUtil.showMessageInfo;

public class CreateLesson implements interfaces.Log, interfaces.GolfInterface{
     private final static String CLASSNAME = utils.LCUtil.getCurrentClassName();

public boolean create(final Lesson lesson, Player player, final Connection conn) throws SQLException    {
        final String methodName = utils.LCUtil.getCurrentMethodName(CLASSNAME); 
        PreparedStatement ps = null;
  try {
            LOG.debug("...entering " + methodName);
            LOG.debug(" with Lesson = " + lesson);
            LOG.debug(" with Player = " + player);

         //   final String query = utils.LCUtil.generateInsertQuery(conn, "schedule"); mod 28-01-2023
            final String query = utils.LCUtil.generateInsertQuery(conn, "lesson");
            ps = conn.prepareStatement(query);
            ps.setNull(1, java.sql.Types.INTEGER);
            ps.setTimestamp(2,Timestamp.valueOf(lesson.getEventStartDate()));
            ps.setTimestamp(3,Timestamp.valueOf(lesson.getEventEndDate()));
            ps.setInt(4,lesson.getEventProId());
            ps.setInt(5,player.getIdplayer());
       //     ps.setInt(5, event.getEventPlayerId());
            ps.setBoolean(6, lesson.isEventAllDay());
            ps.setString(7, lesson.getEventTitle());
            lesson.setEventDescription(player.getPlayerLastName() + ", " + player.getPlayerFirstName()
                 + " (" + player.getIdplayer() + ")"); // contrgetEventPlayerId()ôle modificatin et suppression
            ps.setString(8, lesson.getEventDescription());
            ps.setTimestamp(9, Timestamp.from(Instant.now()));
            utils.LCUtil.logps(ps); 
            int row = ps.executeUpdate(); // + write into database
            if (row != 0){
                String msg = "Lesson Created = " + lesson;
                LOG.info(msg);
      //          showMessageInfo(msg);
                return true;
            } else {
                String msg = "<br/>ERROR insert Lesson : " + lesson;
                LOG.debug(msg);
                showMessageFatal(msg);
                return false;
            }
   }catch (SQLException sqle) {
            String msg = "SQLException in " + methodName + sqle.getMessage() + " ,SQLState = "
                    + sqle.getSQLState() + " ,ErrorCode = " + sqle.getErrorCode();
            LOG.error(msg);
            showMessageFatal(msg);
            return false;
    } catch (Exception e) {
            String msg = "£££ Exception in " + methodName + e.getMessage();
            LOG.error(msg);
            showMessageFatal(msg);
            return false;
        //return null;
    } finally {
            DBConnection.closeQuietly(null, null, null, ps); // new 14/8/2014
        }
    } //end method
void main() throws SQLException, Exception{
      Connection conn = new DBConnection().getConnection();
try{
   Lesson event = new Lesson();
   event.setEventStartDate(LocalDateTime.parse("2021-05-30T15:45:00"));
   event.setEventEndDate(LocalDateTime.parse  ("2021-05-30T16:15:00"));
   event.setEventProId(3); //olivier 324715
   event.setEventAllDay(true);
   event.setEventTitle("Golf lesson Bernard Nicolay");
   
   Player player = new Player();
   player.setIdplayer(206658);
   player = new read.ReadPlayer().read(player, conn);
 //  event.setEventDescription("event's description"); generated by program
    boolean lp = new CreateLesson().create(event, player, conn);
        LOG.debug("from main, after lp = " + lp);
 } catch (Exception e) {
            String msg = "Â£Â£ Exception in main = " + e.getMessage();
            LOG.error(msg);
   }finally{
         DBConnection.closeQuietly(conn, null, null , null); 
   }
   } // end main
} //end 