# turn on statement pooling
# https://www.mchange.com/projects/c3p0/#c3p0_properties
# ce fichier n'est pas utilis\u00e9 !!

c3p0.maxStatements=150
minPoolSize=2
initialPoolSize=3
maxPoolSize=16
# close pooled Connections that go unused for more than half an hour
c3p0.maxIdleTime=1800