#start
jdbc.dbname=golflc
jdbc.host=localhost:3308/
jdbc.mysql=jdbc:mysql://
#attention dans le datasource file mysql-ds.xml remplacer & par &amp;
jdbc.params=?AllowMultiQueries=true&AllowUserVariables=true&useSSL=false&allowPublicKeyRetrieval=true&nullNamePatternMatchesAll=true&useUnicode=true&characterEncoding=UTF-8
jdbc.datasource=java:jboss/datasources/golflc
#end
#&allowPublicKeyRetrieval=true 31-07-2023 java.sql.SQLNonTransientConnectionException: Public Key Retrieval is not allowed 