
# http://www.quartz-scheduler.org/documentation/2.3.1-SNAPSHOT/configuration.html#configuration-of-listeners-your-application-can-receive-notification-of-scheduled-events -->
# http://www.quartz-scheduler.org/documentation/quartz-2.3.0/quick-start.html
# http://www.quartz-scheduler.org/documentation/quartz-2.3.0/configuration/

#   ce fichier n'est pas lu !!!!!!

# Generic configuration - probably not needed, most of this is just the defaults
org.quartz.scheduler.instanceName = MyScheduler
org.quartz.scheduler.instanceId = 1
org.quartz.scheduler.rmi.export = false
org.quartz.scheduler.rmi.proxy = false
org.quartz.threadPool.threadCount = 1
org.quartz.threadPool.threadPriority: 5
org.quartz.threadPool.class = org.quartz.simpl.SimpleThreadPool
# in memory execution
# org.quartz.jobStore.class = org.quartz.simpl.RAMJobStore

# Database properties : from 25-06-2021

org.quartz.jobStore.class=org.quartz.impl.jdbcjobstore.JobStoreTX
org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.StdJDBCDelegate
org.quartz.jobStore.dataSource=quartzDataSource
org.quartz.jobStore.tablePrefix=QRTZ_

# org.quartz.threadPool.class=org.quartz.simpl.SimpleThreadPool
# <driver-class>com.mysql.cj.jdbc.Driver</driver-class>
# old was : org.quartz.dataSource.quartzDataSource.driver=com.mysql.jdbc.Driver

org.quartz.dataSource.quartzDataSource.driver=com.mysql.cj.jdbc.Driver
org.quartz.dataSource.quartzDataSource.URL=jdbc:mysql://localhost:3306/quartz_schema
org.quartz.dataSource.quartzDataSource.user=*****
org.quartz.dataSource.quartzDataSource.password=*****

# 24-06-2021  https://examples.javacodegeeks.com/enterprise-java/quartz/java-quartz-best-practices-example/

org.quartz.scheduler.skipUpdateCheck=false

# Configure it to look in the quartz.xml for the job schedules
# org.quartz.plugin.jobInitializer.class instructs quartz to use XMLSchedulingDataProcessorPlugin
# for job and trigger definitions and add them to scheduler while initialization

org.quartz.plugin.jobInitializer.class = org.quartz.plugins.xml.XMLSchedulingDataProcessorPlugin

# org.quartz.plugin.jobInitializer.fileNames =C:/Users/Collet/Documents/NetBeansProjects/GolfWfly/src/main/resources/quartz-config.xml

org.quartz.plugin.jobInitializer.fileNames = quartz-config.xml
org.quartz.plugin.jobInitializer.failOnFileNotFound = true

# scanInterval: the xml definition files can be reloaded if a file change is detected.
# This is the interval (in seconds) the files are looked at. Set to 0 to disable scanning.
org.quartz.plugin.jobInitializer.scanInterval = 6000

# new 01/07/02021  https://medium.com/@himsmittal/quartz-plugins-a-must-have-for-all-quartz-implementations-7ca01e98e620
# org.quartz.plugin.jobHistory.class=org.quartz.plugins.history.LoggingJobHistoryPlugin
# Format of Log Generated
# org.quartz.plugin.jobHistory.jobSuccessMessage=Job [{1}.{0}] execution complete and reports: {8}org.quartz.plugin.jobHistory.jobToBeFiredMessage=Job [{1}.{0}] to be fired by trigger [{4}.{3}], re-fire: {7}