# Application Properties -- 
settings.title=This is the file golflc_settings.properties
settings.LC=Welcome Louis !
timeout=600 # 1 minute - en seconds
324713=Administrator
654333=Administrator
settings.execution=no DEBUG (from settings properties)
#settings.userhome=C:/Users/Collet mod 03-08-2023
#settings.userapp=/Documents/NetBeansProjects/GolfWfly_old
settings.userapp=/Documents/NetBeansProjects/GolfJakarta
# Mail password remplac\u00e9 23-11-2025 par env variable