
package security;

import static interfaces.Log.LOG;
import jakarta.enterprise.context.RequestScoped;
import jakarta.enterprise.inject.Alternative;
import jakarta.inject.Inject;
import jakarta.security.enterprise.AuthenticationStatus;
import jakarta.security.enterprise.authentication.mechanism.http.HttpAuthenticationMechanism;
import jakarta.security.enterprise.authentication.mechanism.http.HttpMessageContext;
import jakarta.security.enterprise.credential.UsernamePasswordCredential;
import jakarta.security.enterprise.identitystore.CredentialValidationResult;
import static jakarta.security.enterprise.identitystore.CredentialValidationResult.Status.VALID;
import jakarta.security.enterprise.identitystore.IdentityStoreHandler;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

@RequestScoped
//@Specializes
//https://stackoverflow.com/questions/45676495/weld-001409-ambiguous-dependencies-for-type-t-with-qualifiers-default
//@ApplicationScoped
//https://stackoverflow.com/questions/10185976/cdi-ambiguous-dependencies
@Alternative // new 07-10-2021 for wildfly 25
public class CustomAuthenticationMechanism implements HttpAuthenticationMechanism {
 
   @Inject
   private IdentityStoreHandler idStoreHandler; // instance CustomIdentityStore generated by container wildfly
 /*
   @Override
   public AuthenticationStatus validateRequest(HttpServletRequest req, 
                                               HttpServletResponse res, 
                                               HttpMessageContext msg) {
       // use idStoreHandler to authenticate and authorize access
       return msg.responseUnauthorized(); // other responses available
   }
   */
   @Override
   public AuthenticationStatus validateRequest(HttpServletRequest req,
                                               HttpServletResponse res,
                                               HttpMessageContext context) {
          LOG.debug("entering customAuthenticationMechanism");
       CredentialValidationResult result = idStoreHandler.validate(new UsernamePasswordCredential(req.getParameter("name"),
               req.getParameter("password")));
       if (result.getStatus() == VALID) {
           return context.notifyContainerAboutLogin(result);
       } else {
           return context.responseUnauthorized();
       }
   }
} // end class