
package security;

import static interfaces.Log.LOG;
import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;
import javax.security.enterprise.AuthenticationStatus;
import javax.security.enterprise.authentication.mechanism.http.HttpAuthenticationMechanism;
import javax.security.enterprise.authentication.mechanism.http.HttpMessageContext;
import javax.security.enterprise.credential.UsernamePasswordCredential;
import javax.security.enterprise.identitystore.CredentialValidationResult;
import static javax.security.enterprise.identitystore.CredentialValidationResult.Status.VALID;
import javax.security.enterprise.identitystore.IdentityStoreHandler;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;


@ApplicationScoped
public class CustomAuthenticationMechanism implements HttpAuthenticationMechanism {
 
   @Inject
   private IdentityStoreHandler idStoreHandler; // instance CustomIdentityStore generated by container wildfly
 /*
   @Override
   public AuthenticationStatus validateRequest(HttpServletRequest req, 
                                               HttpServletResponse res, 
                                               HttpMessageContext msg) {
       // use idStoreHandler to authenticate and authorize access
       return msg.responseUnauthorized(); // other responses available
   }
   */
   @Override
   public AuthenticationStatus validateRequest(HttpServletRequest req,
                                               HttpServletResponse res,
                                               HttpMessageContext context) {
       LOG.info("entering customAuthenticationMechanism");
       CredentialValidationResult result = idStoreHandler.validate(new UsernamePasswordCredential(req.getParameter("name"),
               req.getParameter("password")));
       if (result.getStatus() == VALID) {
           return context.notifyContainerAboutLogin(result);
       } else {
           return context.responseUnauthorized();
       }
   }
   
} // end class

